### ISSUE TITLE
Why not on crates.io?

### ISSUE THREAD

**Issue by nestordemeure** [pengowen123/cmaes#2]
I was surprised to discovered that I couldn't find an implementation of CMA-ES on crates.io and further suprised to discover that your, apparently polished and ready for use, implementation exists but is not published there.

Is there a reason for that?

**Comment by pengowen123** [comment]
Sorry for the late response. There was an issue preventing the library from solving some problems consistently, but I was unable to find the source of it. I'd want to fix this before pushing it to crates.io.

**Comment by nestordemeure** [comment]
Ok, thank you for the answer! It would be great to have an implementation of CMA-ES on crates.io. Would you mind creating an issue documenting the problem you had (or at least what you remember about it)? I have no time to take a look right now but would be glad to help at some point.

**Comment by pengowen123** [comment]
I'll have time to look into it myself, but I'll open an issue with whatever I find if I don't finish it.

**Comment by pengowen123** [comment]
cc @nestordemeure I rewrote the library to be much more robust, and it's now up on crates.io.

**Comment by nestordemeure** [comment]
Great!
