### ISSUE TITLE
More documentation on dependencies

### ISSUE THREAD

**Issue by JulianRuiseco** [pengowen123/cmaes#3]
I was trying to give this a shot, but I haven't been able to puzzle out how to get net-lib to compile. 

It's a bit unclear what dependencies are exactly required, and whether windows is a good idea or if it's best to go straight to linux.

The project looks absolutely fantastic, looking forward to trying it out for a physics engines meta-parameters!

**Comment by pengowen123** [comment]
Building on Windows seems to be a lot of trouble, and I haven't been able to get it to work. The closest I've gotten is by enabling the `intel-mkl` feature for `nalgebra-lapack` to avoid compiling netlib, but I run into an error compiling `zstd-sys` (see [this issue](https://github.com/gyscos/zstd-rs/issues/102#issuecomment-1049330080)). I'll update the README, but for now the easiest solution is to build it on linux.

**Comment by JulianRuiseco** [comment]
Mandating Linux is a reasonable constraint.
